# Generated by Django 4.2.5 on 2023-10-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tickers_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created_at',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tickers'),
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
