# Generated by Django 4.2.5 on 2023-11-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_comment_content_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
