# Generated by Django 4.2.5 on 2023-11-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_topic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='content',
            new_name='description',
        ),
    ]
