# Generated by Django 4.1.5 on 2023-10-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickers',
            old_name='bse_code',
            new_name='bseCode',
        ),
        migrations.RenameField(
            model_name='tickers',
            old_name='nse_code',
            new_name='nseCode',
        ),
    ]
