# Generated by Django 4.2.5 on 2023-11-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='customer',
        ),
    ]
