# Generated by Django 4.2.5 on 2023-11-09 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_user_watchlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
